name: Testing the function and provisioning
on:
    push:
      branches: [ "main" ]
      paths:
        - 'backend/**'
        - 'terraform/**'
    workflow_dispatch:

permissions:
    contents: read

jobs:
    Terraform:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Login to azure
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
            - name: Terraform Init
              run: terraform init -input=false
            - name: Terraform Plan
              run: terraform plan -input=false